// Generated by CoffeeScript 1.3.1
(function() {

  exports.create = function() {
    console.log("create a map in 3.2..1 let's go");
    return {
      "def": "abc",
      "fed": 123,
      "edf": false
    };
  };

}).call(this);
